// /reports — plain-text "share summary" of the Weekly Brief, built from the
// same useBriefData queries the preview renders, honoring the section toggles.
// Meant for the clipboard → WhatsApp / e-mail; keep it terse and ASCII-safe.
import { fmtInt, fmtNum, fmtPct, dateLabel, monthLabel } from '../../lib/format.js';

const isOpenAlert = (a) => !/ack/i.test(String(a?.status || ''));
const sevRank = (s) => ({ critical: 3, high: 2, medium: 1 }[String(s || '').toLowerCase()] ?? 0);

export function buildShareSummary(brief, sections = {}) {
  const on = (k) => sections[k] !== false;
  const { win } = brief;
  const lines = [
    `DAPPA Weekly Intelligence Brief — ${win.label} (${dateLabel(win.from)} to ${dateLabel(win.to)})`,
    'Karnataka State Police · synthetic demo data',
    '',
  ];

  if (on('kpis') && brief.kpis.data) {
    const k = brief.kpis.data;
    const det = Number(k.detectionRate) <= 1 ? Number(k.detectionRate) * 100 : Number(k.detectionRate);
    const mom = Number.isFinite(Number(k.momPct)) ? fmtPct(Number(k.momPct), { sign: true, fraction: false }) : '—';
    lines.push(
      `Headline: ${fmtInt(k.totalFirs)} FIRs (${mom} MoM) · ${fmtInt(k.heinousCount)} heinous · detection ${Number.isFinite(det) ? `${det.toFixed(1)}%` : '—'} · ${fmtInt(k.activeAlerts)} open alerts`,
      '',
    );
  }

  if (on('alerts')) {
    const top = (brief.alerts.data || []).filter(isOpenAlert)
      .sort((a, b) => sevRank(b.severity) - sevRank(a.severity) || Math.abs(b.zScore || 0) - Math.abs(a.zScore || 0))
      .slice(0, 5);
    if (top.length) {
      lines.push('Top anomaly alerts:');
      top.forEach((a, i) => {
        lines.push(`  ${i + 1}. [${String(a.severity || '—')}] ${a.headName || 'Anomaly'} — ${a.districtName || a.districtId || '?'} (z ${fmtNum(a.zScore, 1)}, ${fmtInt(a.observed)} obs vs ${fmtInt(a.expected)} expected)`);
      });
      lines.push('');
    }
  }

  if (on('hotspots')) {
    const top = [...(brief.hotspots.data || [])]
      .sort((a, b) => (Number(b.intensity) || 0) - (Number(a.intensity) || 0))
      .slice(0, 3);
    if (top.length) {
      lines.push(`Hotspots: ${top.map((h) => `${h.label || `Cluster ${h.clusterId}`} (${fmtInt(h.caseCount)} cases)`).join(' · ')}`, '');
    }
  }

  if (on('network')) {
    const nodes = brief.network.data?.nodes || [];
    if (nodes.length) {
      const communities = new Set(nodes.map((n) => n.communityId ?? '—')).size;
      lines.push(`Network: ${fmtInt(nodes.length)} resolved offenders across ${fmtInt(communities)} co-offending groups`, '');
    }
  }

  if (on('forecast')) {
    const f = (brief.forecast.data?.forecast || [])[0];
    if (f) {
      lines.push(`Forecast: ${monthLabel(f.ym)} ≈ ${fmtInt(f.predicted)} FIRs (${fmtInt(f.lo)}–${fmtInt(f.hi)})${brief.forecast.data?.model ? ` · model ${brief.forecast.data.model}` : ''}`);
    }
    const risk = [...(brief.risk.data || [])]
      .sort((a, b) => (Number(b.riskScore) || 0) - (Number(a.riskScore) || 0))
      .slice(0, 3);
    if (risk.length) {
      lines.push(`Highest-risk stations: ${risk.map((s) => `${s.unitName || s.unitId} (${fmtNum(s.riskScore, 2)})`).join(' · ')}`);
    }
    if (f || risk.length) lines.push('');
  }

  lines.push('Generated by DAPPA (Zoho Catalyst) — all figures from synthetic data, not real crime records.');
  return lines.join('\n');
}
