#!/usr/bin/env node
// gen_contracts.mjs — docs/CONTRACTS.md carries a GENERATED endpoint table and
// a GENERATED flag table, so the documented API can never lag the registered
// one again (the hand-written list documented 24 of 74 routes and 6 of 14
// flags on 27 Aug 2026).
//
//   node scripts/gen_contracts.mjs          # rewrite the two blocks in docs/CONTRACTS.md
//   node scripts/gen_contracts.mjs --check  # exit 1 if they would change (contract suite + CI)
//
// Routes are enumerated WITHOUT starting the server: every lib/routes/*.js
// module exports register(router); an express Router records verb + path.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const API = path.join(ROOT, 'functions/dappa_api');
const require = createRequire(path.join(API, 'package.json'));
const CHECK = process.argv.includes('--check');

const express = require('express');
const routesDir = path.join(API, 'lib/routes');
const files = fs.readdirSync(routesDir).filter((f) => f.endsWith('.js')).sort();
const rows = [];
for (const f of files) {
  const mod = require(path.join(routesDir, f));
  if (typeof mod.register !== 'function') continue;
  const router = express.Router();
  mod.register(router);
  for (const layer of router.stack) {
    if (!layer.route) continue;
    for (const verb of Object.keys(layer.route.methods)) rows.push({ verb: verb.toUpperCase(), path: layer.route.path, file: `lib/routes/${f}` });
  }
}
rows.sort((a, b) => a.path.localeCompare(b.path) || a.verb.localeCompare(b.verb));
const distinct = new Set(rows.map((r) => r.path)).size;

// service each path exercises, from servicemap endpoints
const { buildServiceMap } = require(path.join(API, 'lib/servicemap.js'));
const svc = buildServiceMap({ flags: {}, services: {} });
const serviceOf = (p) => svc.filter((s) => (s.endpoints || []).some((e) => e.split(' ')[0] === p)).map((s) => s.name).join(', ');

const endpointBlock = [
  '<!-- ENDPOINTS:START — generated by scripts/gen_contracts.mjs from lib/routes/*.js; do not edit by hand -->',
  `**${rows.length} registrations, ${distinct} distinct paths**, all mounted at both \`/api/v1\` and \`/server/dappa_api/api/v1\`. Every path is exercised by \`functions/dappa_api/test/run.mjs\`.`,
  '',
  '| Verb | Path | Owner | Catalyst service it exercises |',
  '|---|---|---|---|',
  ...rows.map((r) => `| ${r.verb} | \`${r.path}\` | \`${r.file}\` | ${serviceOf(r.path) || '—'} |`),
  '<!-- ENDPOINTS:END -->',
].join('\n');

const flagsSrc = fs.readFileSync(path.join(API, 'lib/flags.js'), 'utf8');
const flagRows = [];
for (const m of flagsSrc.matchAll(/(\w+): flagOn\('([A-Z_]+)',\s*(true|false)\)/g)) {
  const owner = svc.find((s) => s.flag === m[2]);
  flagRows.push(`| \`${m[2]}\` | \`flags.${m[1]}\` | default **${m[3] === 'true' ? 'on' : 'off'}** | ${owner ? owner.name : 'platform behaviour'} | ${owner && owner.requires && owner.requires.length ? owner.requires.map((r) => `\`${r}\``).join(', ') : '—'} |`);
}
const flagBlock = [
  '<!-- FLAGS:START — generated by scripts/gen_contracts.mjs from lib/flags.js + lib/servicemap.js; do not edit by hand -->',
  '| Env var | Flag | Default | Gates | Prerequisite env |',
  '|---|---|---|---|---|',
  ...flagRows,
  '',
  'Every fallback keeps the identical response shape and sets `meta.source:"fallback-local"`; a flag that is on with an empty prerequisite reports `console-pending` on `GET /meta/services`.',
  '<!-- FLAGS:END -->',
].join('\n');

const docPath = path.join(ROOT, 'docs/CONTRACTS.md');
const doc = fs.readFileSync(docPath, 'utf8');
const reE = /<!-- ENDPOINTS:START[\s\S]*?<!-- ENDPOINTS:END -->/;
const reF = /<!-- FLAGS:START[\s\S]*?<!-- FLAGS:END -->/;
if (!reE.test(doc) || !reF.test(doc)) { console.error('docs/CONTRACTS.md is missing the ENDPOINTS or FLAGS marker block'); process.exit(2); }
const next = doc.replace(reE, endpointBlock).replace(reF, flagBlock);
if (CHECK) {
  if (next !== doc) { console.error('docs/CONTRACTS.md is STALE — run `node scripts/gen_contracts.mjs` and commit it'); process.exit(1); }
  console.log(`contracts OK — ${rows.length} registrations / ${distinct} paths, ${flagRows.length} flags documented`);
  process.exit(0);
}
fs.writeFileSync(docPath, next);
console.log(`contracts written — ${rows.length} registrations / ${distinct} paths, ${flagRows.length} flags; docs/CONTRACTS.md ${next !== doc ? 'updated' : 'unchanged'}`);
