#!/usr/bin/env node
// gen_service_table.mjs — the README's Catalyst-services table is GENERATED
// from functions/dappa_api/lib/servicemap.js, so it can never drift from the
// code again (the old hand-written table listed 16 of 28 services and called
// Circuits "roadmap" while lib/circuits.js already called it).
//
//   node scripts/gen_service_table.mjs          # rewrite README.md between the markers + docs/service_table.json
//   node scripts/gen_service_table.mjs --check  # exit 1 if README/json would change (contract suite + CI)
//
// Status is evaluated against the TRACKED catalyst-config.json (flags + which
// env vars are set), i.e. the state a fresh `catalyst deploy` produces. Values
// set only in the console are not visible here; the live truth is always
// GET /meta/services, which the About page renders.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const CHECK = process.argv.includes('--check');

const config = JSON.parse(fs.readFileSync(path.join(ROOT, 'functions/dappa_api/catalyst-config.json'), 'utf8'));
const env = (config.deployment && config.deployment.env_variables) || {};
// servicemap reads process.env for the "requires" check — mirror the tracked config
for (const [k, v] of Object.entries(env)) process.env[k] = v;

const flagsMod = require(path.join(ROOT, 'functions/dappa_api/lib/flags.js'));
const { buildServiceMap, summarize } = require(path.join(ROOT, 'functions/dappa_api/lib/servicemap.js'));
const flags = flagsMod.getFlags();
// Services that exist only as console handles (bucket, NoSQL table) cannot be
// probed from the workstation; report them as the code reports them when the
// handle is present, since both are live on the deployment (see /healthz).
const ctx = { flags, services: { artifactBucket: true, graphLoaders: { nosql: true, stratus: true } } };
const rows = buildServiceMap(ctx);
const summary = summarize(rows);

const STATUS_LABEL = {
  live: 'live', active: 'active (flag on)', platform: 'platform', 'flag-gated': 'flag-gated', 'console-pending': 'console-pending', unavailable: 'unavailable in IN DC',
};
const CATEGORY_ORDER = ['compute', 'data', 'messaging', 'orchestration', 'ai', 'platform'];
const sorted = [...rows].sort((a, b) => CATEGORY_ORDER.indexOf(a.category) - CATEGORY_ORDER.indexOf(b.category));

function cell(s) { return String(s || '').replace(/\|/g, '\\|'); }
const lines = [];
lines.push(`| # | Service | Category | Status | How DAPPA calls it | Console step / flag |`);
lines.push(`|---|---|---|---|---|---|`);
sorted.forEach((r, i) => {
  const step = (r.status === 'console-pending' || r.status === 'unavailable') ? cell(r.statusReason) : (r.flag ? `\`${r.flag}\`` : '—');
  lines.push(`| ${i + 1} | ${cell(r.name)} | ${r.category} | ${STATUS_LABEL[r.status] || r.status} | ${cell(r.invocation || '— (no call site)')} | ${step} |`);
});
const counts = summary.byStatus;
const block = [
  `<!-- SERVICES:START — generated by scripts/gen_service_table.mjs from functions/dappa_api/lib/servicemap.js; do not edit by hand -->`,
  `**${summary.total} Catalyst services** are mapped by \`GET /meta/services\`; **${summary.reachableFromCode}** have a real call site in this repository. Against the tracked configuration: ${counts.live || 0} live, ${counts.active || 0} active behind a flag, ${counts.platform || 0} platform, ${counts['flag-gated'] || 0} flag-gated, ${counts['console-pending'] || 0} console-pending, ${counts.unavailable || 0} unavailable in the IN data centre. The deployed truth is always the live endpoint — the \`/about\` page renders it.`,
  ``,
  ...lines,
  ``,
  `*Status vocabulary:* **live** — called on the default request path; **active** — flag on and configured; **flag-gated** — code path exists, flag off; **console-pending** — needs a console step no code can perform (the reason names it); **platform** — the project runs on it without an SDK call from the function; **unavailable in IN DC** — the Catalyst docs list the service as not offered in the IN data centre this project runs in, so no console step can enable it (the reason cites the research page).`,
  `<!-- SERVICES:END -->`,
].join('\n');

// ---- environment-variable table: one row per flag (default from lib/flags.js) and per prerequisite
const flagsSrc = fs.readFileSync(path.join(ROOT, 'functions/dappa_api/lib/flags.js'), 'utf8');
const flagDefaults = {};
for (const m of flagsSrc.matchAll(/flagOn\('([A-Z_]+)',\s*(true|false)\)/g)) flagDefaults[m[1]] = m[2] === 'true';
const envRows = [];
for (const r of sorted) {
  if (!r.flag && !(r.requires && r.requires.length)) continue;
  const shipped = env[r.flag] !== undefined ? `\`${env[r.flag]}\`` : '(unset)';
  if (r.flag) envRows.push(`| \`${r.flag}\` | flag | ${r.name} — off → ${cell(r.fallback)} | default ${flagDefaults[r.flag] ? 'on' : 'off'}; tracked config ${shipped} |`);
  for (const req of r.requires || []) {
    if (req === 'APP_BASE_URL') continue; // documented in the general table
    envRows.push(`| \`${req}\` | prerequisite | ${r.name}; empty ⇒ \`console-pending\` | console step (see docs/CONSOLE_SETUP.md); set via \`.env.deploy\` |`);
  }
}
if (env.QUICKML_STATUS_ENDPOINT_KEY !== undefined) envRows.push('| `QUICKML_STATUS_ENDPOINT_KEY` | prerequisite | QuickML case-status Random Forest endpoint (`POST /predict/case-status`) | published endpoint key; set via `.env.deploy`, never committed |');
const envBlock = [
  `<!-- ENV:START — generated by scripts/gen_service_table.mjs; do not edit by hand -->`,
  `| Variable | Kind | Controls | Default / where it is set |`,
  `|---|---|---|---|`,
  ...envRows,
  `<!-- ENV:END -->`,
].join('\n');

const readmePath = path.join(ROOT, 'README.md');
const readme = fs.readFileSync(readmePath, 'utf8');
const re = /<!-- SERVICES:START[\s\S]*?<!-- SERVICES:END -->/;
const reEnv = /<!-- ENV:START[\s\S]*?<!-- ENV:END -->/;
if (!re.test(readme) || !reEnv.test(readme)) {
  console.error('README.md is missing the SERVICES or ENV marker block');
  process.exit(2);
}
const nextReadme = readme.replace(re, block).replace(reEnv, envBlock);

const json = {
  generatedFrom: 'functions/dappa_api/lib/servicemap.js',
  note: 'status evaluated against the tracked catalyst-config.json; live truth is GET /meta/services',
  summary,
  services: sorted.map((r) => ({ key: r.key, name: r.name, category: r.category, status: r.status, statusReason: r.statusReason, invocation: r.invocation, flag: r.flag || null, requires: r.requires || [], endpoints: r.endpoints || [] })),
};
const jsonPath = path.join(ROOT, 'docs/service_table.json');
const nextJson = JSON.stringify(json, null, 2) + '\n';
const prevJson = fs.existsSync(jsonPath) ? fs.readFileSync(jsonPath, 'utf8') : '';

const changed = nextReadme !== readme || nextJson !== prevJson;
if (CHECK) {
  if (changed) {
    console.error('service table is STALE — run `node scripts/gen_service_table.mjs` and commit README.md + docs/service_table.json');
    process.exit(1);
  }
  console.log(`service table OK — ${summary.total} services, README and docs/service_table.json match servicemap.js`);
  process.exit(0);
}
fs.writeFileSync(readmePath, nextReadme);
fs.writeFileSync(jsonPath, nextJson);
console.log(`service table written — ${summary.total} services (${JSON.stringify(counts)}); README.md ${nextReadme !== readme ? 'updated' : 'unchanged'}, docs/service_table.json ${nextJson !== prevJson ? 'updated' : 'unchanged'}`);
